/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import java.applet.AudioClip;

/**
 *
 * @author IVAN
 */
public class calculadora extends javax.swing.JFrame {

    public float primernumero;
    public float segundonumero;
    public String operador;
            /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        lbl_pantalla = new javax.swing.JLabel();
        btm_borrar = new javax.swing.JButton();
        btm_division = new javax.swing.JButton();
        btm_multiplicar = new javax.swing.JButton();
        btm_restar = new javax.swing.JButton();
        btm_igual = new javax.swing.JButton();
        btm_punto = new javax.swing.JButton();
        btm_siete = new javax.swing.JButton();
        btm_ocho = new javax.swing.JButton();
        btm_nueve = new javax.swing.JButton();
        btm_cuatro = new javax.swing.JButton();
        btm_cinco = new javax.swing.JButton();
        btm_seis = new javax.swing.JButton();
        btm_uno = new javax.swing.JButton();
        btm_dos = new javax.swing.JButton();
        btm_tres = new javax.swing.JButton();
        btm_cero = new javax.swing.JButton();
        btm_sumar = new javax.swing.JButton();
        lbl_marca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_opciones = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_historial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_mu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_pantalla.setBackground(new java.awt.Color(255, 255, 255));
        lbl_pantalla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_pantalla.setOpaque(true);

        btm_borrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_borrar.setText("C");
        btm_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_borrarMouseClicked(evt);
            }
        });
        btm_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_borrarActionPerformed(evt);
            }
        });

        btm_division.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_division.setText("/");
        btm_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_divisionMouseClicked(evt);
            }
        });
        btm_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_divisionActionPerformed(evt);
            }
        });

        btm_multiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_multiplicar.setText("*");
        btm_multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_multiplicarMouseClicked(evt);
            }
        });
        btm_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_multiplicarActionPerformed(evt);
            }
        });

        btm_restar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_restar.setText("-");
        btm_restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_restarMouseClicked(evt);
            }
        });
        btm_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_restarActionPerformed(evt);
            }
        });

        btm_igual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_igual.setText("=");
        btm_igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_igualMouseClicked(evt);
            }
        });
        btm_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_igualActionPerformed(evt);
            }
        });

        btm_punto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_punto.setText(".");
        btm_punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_puntoMouseClicked(evt);
            }
        });
        btm_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_puntoActionPerformed(evt);
            }
        });

        btm_siete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_siete.setText("7");
        btm_siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_sieteMouseClicked(evt);
            }
        });
        btm_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_sieteActionPerformed(evt);
            }
        });

        btm_ocho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_ocho.setText("8");
        btm_ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_ochoMouseClicked(evt);
            }
        });
        btm_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_ochoActionPerformed(evt);
            }
        });

        btm_nueve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_nueve.setText("9");
        btm_nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_nueveMouseClicked(evt);
            }
        });
        btm_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_nueveActionPerformed(evt);
            }
        });

        btm_cuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_cuatro.setText("4");
        btm_cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_cuatroMouseClicked(evt);
            }
        });
        btm_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cuatroActionPerformed(evt);
            }
        });

        btm_cinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_cinco.setText("5");
        btm_cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_cincoMouseClicked(evt);
            }
        });
        btm_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cincoActionPerformed(evt);
            }
        });

        btm_seis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_seis.setText("6");
        btm_seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_seisMouseClicked(evt);
            }
        });
        btm_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_seisActionPerformed(evt);
            }
        });

        btm_uno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_uno.setText("1");
        btm_uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_unoMouseClicked(evt);
            }
        });
        btm_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_unoActionPerformed(evt);
            }
        });

        btm_dos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_dos.setText("2");
        btm_dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_dosMouseClicked(evt);
            }
        });
        btm_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_dosActionPerformed(evt);
            }
        });

        btm_tres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_tres.setText("3");
        btm_tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_tresMouseClicked(evt);
            }
        });
        btm_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_tresActionPerformed(evt);
            }
        });

        btm_cero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_cero.setText("0");
        btm_cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_ceroMouseClicked(evt);
            }
        });
        btm_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_ceroActionPerformed(evt);
            }
        });

        btm_sumar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btm_sumar.setText("+");
        btm_sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_sumarMouseClicked(evt);
            }
        });
        btm_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_sumarActionPerformed(evt);
            }
        });

        lbl_marca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_marca.setText("LIM");
        lbl_marca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_marca.setOpaque(true);

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(btm_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btm_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(btm_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btm_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btm_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btm_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(btm_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btm_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btm_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btm_sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(lbl_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btm_division, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btm_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(btm_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btm_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btm_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btm_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btm_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btm_division, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btm_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btm_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btm_sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btm_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btm_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btm_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btm_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btm_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_opciones.setText("Opciones");

        menu_nuevo.setText("Nuevo");
        menu_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevoActionPerformed(evt);
            }
        });
        menu_opciones.add(menu_nuevo);

        menu_historial.setText("Histotial");
        menu_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_historialActionPerformed(evt);
            }
        });
        menu_opciones.add(menu_historial);

        jMenuBar1.add(menu_opciones);

        jMenu2.setText("Ayuda");

        menu_mu.setText("Manual de usuario");
        jMenu2.add(menu_mu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_ceroActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"0");
    }//GEN-LAST:event_btm_ceroActionPerformed

    private void btm_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_unoActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"1");
    }//GEN-LAST:event_btm_unoActionPerformed

    private void btm_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_dosActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"2");
    }//GEN-LAST:event_btm_dosActionPerformed

    private void btm_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_tresActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"3");
    }//GEN-LAST:event_btm_tresActionPerformed

    private void btm_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cuatroActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"4");
    }//GEN-LAST:event_btm_cuatroActionPerformed

    private void btm_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cincoActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"5");
    }//GEN-LAST:event_btm_cincoActionPerformed

    private void btm_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_seisActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"6");
    }//GEN-LAST:event_btm_seisActionPerformed

    private void btm_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_sieteActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"7");
    }//GEN-LAST:event_btm_sieteActionPerformed

    private void btm_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_ochoActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"8");
    }//GEN-LAST:event_btm_ochoActionPerformed

    private void btm_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_nueveActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText(this.lbl_pantalla.getText()+"9");
    }//GEN-LAST:event_btm_nueveActionPerformed

    private void btm_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_borrarActionPerformed
        // TODO add your handling code here:
        this.lbl_pantalla.setText("");
    }//GEN-LAST:event_btm_borrarActionPerformed

    private void btm_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_sumarActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.lbl_pantalla.getText());
        this.operador="+";
        this.lbl_pantalla.setText("");
    }//GEN-LAST:event_btm_sumarActionPerformed

    private void btm_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_igualActionPerformed
        // TODO add your handling code here:
        this.segundonumero=Float.parseFloat(this.lbl_pantalla.getText());
        
        switch(this.operador){
            case "+":this.lbl_pantalla.setText(sincero(this.primernumero+this.segundonumero));break;
            case "-":this.lbl_pantalla.setText(sincero(this.primernumero-this.segundonumero));break;
            case "*":this.lbl_pantalla.setText(sincero(this.primernumero*this.segundonumero));break;
            case "/":
                if(this.segundonumero==0){this.lbl_pantalla.setText("ERRROR");}
                else{
                this.lbl_pantalla.setText(sincero(this.primernumero/this.segundonumero));}break;
        }
        
    }//GEN-LAST:event_btm_igualActionPerformed

    private void btm_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_restarActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.lbl_pantalla.getText());
        this.operador="-";
        this.lbl_pantalla.setText("");
    }//GEN-LAST:event_btm_restarActionPerformed

    private void btm_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_multiplicarActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.lbl_pantalla.getText());
        this.operador="*";
        this.lbl_pantalla.setText("");
    }//GEN-LAST:event_btm_multiplicarActionPerformed

    private void btm_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_divisionActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.lbl_pantalla.getText());
        this.operador="/";
        this.lbl_pantalla.setText("");
    }//GEN-LAST:event_btm_divisionActionPerformed

    private void btm_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_puntoActionPerformed
        // TODO add your handling code here:
        if(!this.lbl_pantalla.getText().contains(".")){
         this.lbl_pantalla.setText(this.lbl_pantalla.getText()+".");   
        }
    }//GEN-LAST:event_btm_puntoActionPerformed

    private void btm_ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_ceroMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
        
    }//GEN-LAST:event_btm_ceroMouseClicked

    private void btm_divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_divisionMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_divisionMouseClicked

    private void btm_multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_multiplicarMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_multiplicarMouseClicked

    private void btm_sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_sieteMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_sieteMouseClicked

    private void btm_ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_ochoMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_ochoMouseClicked

    private void btm_nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_nueveMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_nueveMouseClicked

    private void btm_restarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_restarMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_restarMouseClicked

    private void btm_cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_cuatroMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_cuatroMouseClicked

    private void btm_cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_cincoMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_cincoMouseClicked

    private void btm_seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_seisMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_seisMouseClicked

    private void btm_sumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_sumarMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_sumarMouseClicked

    private void btm_unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_unoMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_unoMouseClicked

    private void btm_dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_dosMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_dosMouseClicked

    private void btm_tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_tresMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_tresMouseClicked

    private void btm_puntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_puntoMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_puntoMouseClicked

    private void btm_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_borrarMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_borrarMouseClicked

    private void btm_igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_igualMouseClicked
        // TODO add your handling code here:
        AudioClip beep;
        beep = java.applet.Applet.newAudioClip(getClass().getResource("/calculadora/beep.wav"));
        beep.play();
    }//GEN-LAST:event_btm_igualMouseClicked

    private void menu_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_nuevoActionPerformed

    private void menu_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_historialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_historialActionPerformed

    public String sincero(float resultado){
    String retorno="";
    retorno=Float.toString(resultado);
    
    if (resultado%1==0){
        retorno=retorno.substring(0, retorno.length()-2);
    }
    return retorno;
    }
    
    
    
    public static void main(String args[]) {
        calculadora play = new calculadora ();
        play.setVisible(true);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_borrar;
    private javax.swing.JButton btm_cero;
    private javax.swing.JButton btm_cinco;
    private javax.swing.JButton btm_cuatro;
    private javax.swing.JButton btm_division;
    private javax.swing.JButton btm_dos;
    private javax.swing.JButton btm_igual;
    private javax.swing.JButton btm_multiplicar;
    private javax.swing.JButton btm_nueve;
    private javax.swing.JButton btm_ocho;
    private javax.swing.JButton btm_punto;
    private javax.swing.JButton btm_restar;
    private javax.swing.JButton btm_seis;
    private javax.swing.JButton btm_siete;
    private javax.swing.JButton btm_sumar;
    private javax.swing.JButton btm_tres;
    private javax.swing.JButton btm_uno;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_pantalla;
    private javax.swing.JMenuItem menu_historial;
    private javax.swing.JMenuItem menu_mu;
    private javax.swing.JMenuItem menu_nuevo;
    private javax.swing.JMenu menu_opciones;
    private javax.swing.JPanel panel_principal;
    // End of variables declaration//GEN-END:variables
}
